In [2]:
import numpy as np


In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
print(arr.dtype)

int64


In [8]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [9]:
Z=np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [10]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ran=np.random.rand(4)
ran

array([0.87572016, 0.95656508, 0.11008145, 0.42557408])

In [12]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

**2D Arrays**

In [13]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
z1=np.zeros([5,5])
z1


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
r1=np.random.rand(4,5)
r1

array([[0.35783534, 0.76227609, 0.11191659, 0.60753383, 0.21535472],
       [0.90174696, 0.26001886, 0.73390499, 0.88230495, 0.22354135],
       [0.49794744, 0.22629552, 0.82256091, 0.92727423, 0.35884432],
       [0.43630634, 0.50305925, 0.19620879, 0.153314  , 0.17955133]])

In [19]:
ar
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(ar.size)

10


In [23]:
print(ar2.size)

9


In [24]:
print(ar.shape)

(10,)


In [25]:
print(ar2.shape)

(3, 3)


**Operations in Array**
copy
reshape
sort

In [26]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ar3[2,2]=10

In [28]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [29]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [30]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [32]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [33]:
ar3.sum()

np.int64(65)

In [34]:
ar3.sum(axis=0)

array([12, 16, 37])

In [35]:
ar3.sum(axis=1)

array([14, 21, 30])

In [36]:
ar4=np.random.rand(99)
ar4

array([0.76050338, 0.44559883, 0.21701979, 0.10337026, 0.32615519,
       0.42037575, 0.40428374, 0.64205653, 0.63543186, 0.84754183,
       0.76643305, 0.31651389, 0.91218151, 0.07948947, 0.451721  ,
       0.94998413, 0.15367013, 0.28490479, 0.60784414, 0.52903472,
       0.13493794, 0.20263553, 0.97577246, 0.8139024 , 0.82258937,
       0.90684767, 0.4381998 , 0.00469108, 0.46099153, 0.16282637,
       0.31040393, 0.14795295, 0.55285054, 0.56868235, 0.74885659,
       0.21164467, 0.22861929, 0.67002118, 0.79899898, 0.8576244 ,
       0.82444871, 0.47517915, 0.16135057, 0.05941932, 0.43667151,
       0.79413799, 0.56748295, 0.76885801, 0.73431936, 0.47519296,
       0.96126828, 0.29854864, 0.47203755, 0.44835045, 0.69201822,
       0.7289017 , 0.5604296 , 0.40354838, 0.65614437, 0.18143653,
       0.33663121, 0.30461678, 0.73933708, 0.87919343, 0.35175082,
       0.67288697, 0.81981571, 0.33927899, 0.58616486, 0.30201942,
       0.19154456, 0.46769162, 0.65946337, 0.39105763, 0.23547

In [37]:
ar4.size

99

In [38]:
ar4=ar4.reshape(11,9)

In [39]:
ar4.size

99

In [44]:
ar4.shape

(11, 9)

In [45]:
ar4


array([[0.76050338, 0.44559883, 0.21701979, 0.10337026, 0.32615519,
        0.42037575, 0.40428374, 0.64205653, 0.63543186],
       [0.84754183, 0.76643305, 0.31651389, 0.91218151, 0.07948947,
        0.451721  , 0.94998413, 0.15367013, 0.28490479],
       [0.60784414, 0.52903472, 0.13493794, 0.20263553, 0.97577246,
        0.8139024 , 0.82258937, 0.90684767, 0.4381998 ],
       [0.00469108, 0.46099153, 0.16282637, 0.31040393, 0.14795295,
        0.55285054, 0.56868235, 0.74885659, 0.21164467],
       [0.22861929, 0.67002118, 0.79899898, 0.8576244 , 0.82444871,
        0.47517915, 0.16135057, 0.05941932, 0.43667151],
       [0.79413799, 0.56748295, 0.76885801, 0.73431936, 0.47519296,
        0.96126828, 0.29854864, 0.47203755, 0.44835045],
       [0.69201822, 0.7289017 , 0.5604296 , 0.40354838, 0.65614437,
        0.18143653, 0.33663121, 0.30461678, 0.73933708],
       [0.87919343, 0.35175082, 0.67288697, 0.81981571, 0.33927899,
        0.58616486, 0.30201942, 0.19154456, 0.46769162],


In [46]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [47]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [48]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
ar=np.delete(ar,6,axis=0)

In [52]:
ar

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [53]:
ar=np.insert(ar,6,6)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:

ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [56]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [10, 12, 15]])

In [57]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [58]:
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [59]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [60]:

ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
ar6[2]

array([[ 3,  5,  8],
       [10, 12, 15]])

In [62]:

ar6[0][0][0]

np.int64(1)

**Scalar Expressions**

add
subtract
multiply
divide
power


In [63]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])

In [64]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 11, 13, 16]])

**Vector Operations**

In [65]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [10, 12, 15]])]

In [66]:
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  9, 13]])

In [67]:
ar8 = np.multiply(ar6[0],ar6[1])
ar8

array([[ 7, 16, 27],
       [ 4, 20, 42]])

In [68]:
ar9 = np.divide(ar6[0],ar6[1])
ar9

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.25      , 0.85714286]])

In [69]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [70]:

np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [71]:

np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

**Statistics**

In [72]:
np.mean(ar5)

np.float64(6.111111111111111)

In [73]:
np.mean(ar5,axis=0)

array([ 4.        ,  5.        ,  6.        ,  4.66666667,  7.        ,
       10.        ])

In [74]:

np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.16666667])

In [75]:

np.median(ar5)

np.float64(5.5)

In [76]:
np.median(ar5,axis=1)

array([2.5, 5. , 9.5])

In [77]:

np.min(ar5)

np.int64(1)

In [78]:

np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [79]:

np.max(ar5,axis=0)

array([ 7,  8,  9, 10, 12, 15])

In [80]:

ar10=np.array([2,5,3,8,0,4,1,6,9])

In [81]:
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9, 10, 12, 15]])